### ISSUE TITLE
GS 3.38 prefs support

### ISSUE THREAD

**Issue by fawtytoo** [PRATAP-KUMAR/rounded-system-menu-buttons#1]
This extension works on GS 3.38 (Debian 11), but the preferences gives this error:
`TypeError: hbox.append is not a function

Stack trace:
  adjustIconSize@/home/steve/.local/share/gnome-shell/extensions/roundedSystemMenuButtons@pratap.fastmail.fm/prefs.js:52:7
  PrefsWidget@/home/steve/.local/share/gnome-shell/extensions/roundedSystemMenuButtons@pratap.fastmail.fm/prefs.js:35:31
  buildPrefsWidget@/home/steve/.local/share/gnome-shell/extensions/roundedSystemMenuButtons@pratap.fastmail.fm/prefs.js:13:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17`

**Comment by pratap-panabaka** [comment]
Hi..
Rite now it's tested in gnome-shell 41 only.
I will adapt the preferences section for 3.38 tomorrow.

**Comment by pratap-panabaka** [comment]
Hi, I have uploaded extension for 3.36 and 3.38 to gnome-extensions website, once it is approved, you can check it.
